-- 1. Create custom profiles/users table in public schema
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text UNIQUE NOT NULL,
  "fullName" text,
  focus_area text DEFAULT 'Sayısal',
  target_goal text DEFAULT 'İlk 5000',
  weekly_hours text DEFAULT '20 Saat',
  focus_time text DEFAULT 'Sabah 🌅',
  daily_goal_hours double precision DEFAULT 4.0,
  profile_pic text,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security (RLS) on users table
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to read their own profile"
  ON public.users FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Allow users to update their own profile"
  ON public.users FOR UPDATE
  USING (auth.uid() = id);

CREATE POLICY "Allow users to insert their own profile"
  ON public.users FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Trigger to automatically create a public profile when a user signs up via Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (id, email, "fullName", focus_area, target_goal, weekly_hours, focus_time, daily_goal_hours)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'fullName', new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    'Sayısal',
    'İlk 5000',
    '20 Saat',
    'Sabah 🌅',
    4.0
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 2. Create tasks table
CREATE TABLE IF NOT EXISTS public.tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  status text DEFAULT 'pending',
  priority_score double precision DEFAULT 1.0,
  subject_name text,
  estimated_time integer DEFAULT 30,
  actual_time integer DEFAULT 0,
  scheduled_date text,
  version integer DEFAULT 1,
  is_deleted boolean DEFAULT false,
  questions_solved integer DEFAULT 0,
  questions_correct integer DEFAULT 0,
  questions_wrong integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on tasks table
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to manage their own tasks"
  ON public.tasks FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- 3. Create errors (Hata Kumbarası) table
CREATE TABLE IF NOT EXISTS public.errors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  image_url text,
  image_data text,
  subject_name text,
  topic_name text,
  difficulty text DEFAULT 'Orta',
  ocr_text text,
  solution_text text,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on errors table
ALTER TABLE public.errors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to manage their own errors"
  ON public.errors FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
